config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :transmissions

  resources :colors

  resources :chasses

  resources :engines

  resources :years

  resources :models

  resources :makes

  resources :emp_jobs

  resources :line_items

  resources :vehicles

  resources :jobs

  resources :appointments

  resources :invoices

  resources :services

  resources :employees

  resources :customers

  resources :surplus_products

  get "/update_price" => "services#update_price"

  root 'customers#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :job


  validates_uniqueness_of :date, scope: [], :message=>"This time is already taken. Please select another time."

end

app/models/chassis.rb
class Chassis < ActiveRecord::Base

  has_many :vehicles
end

app/models/color.rb
class Color < ActiveRecord::Base

  has_many :vehicles
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :invoices
  has_many :vehicles


  def show_full_name
    "#{fname} #{lname}"
  end

end

app/models/emp_job.rb
class EmpJob < ActiveRecord::Base

  # belongs_to :employee
  # belongs_to :job
end

app/models/employee.rb
class Employee < ActiveRecord::Base

  # has_many :emp_jobs
  # has_many :jobs, through: :emp_jobs

  has_many :jobs
  has_many :line_items


  def show_full_name
    "#{fname} #{lname}"
  end


  def show_active
    if status?
      "Active"
    else
      "Inactive"
    end
  end
end

app/models/engine.rb
class Engine < ActiveRecord::Base

  has_many :vehicles
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer


  def show_paid
    if paid?
      "Paid"
    else
      "Due"
    end
  end

end

app/models/job.rb
class Job < ActiveRecord::Base

  has_many :appointments
  has_many :line_items, dependent: :destroy
  has_many :surplus_products
  # has_many :emp_jobs
  # has_many :employees, through: :emp_jobs

  belongs_to :employee
  belongs_to :vehicle
  belongs_to :invoice, dependent: :destroy


  before_create :auto_create_invoice
  after_update :update_invoice_subtotal


  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Finished"
    else
      "In Progress"
    end
  end

  #when a job is marked complete, update invoice subtotal
  def update_invoice_subtotal
    if self.complete?
      Invoice.update(self.invoice_id, :subtotal => self.amount)

      newTax = self.amount * 0.0625

      Invoice.update(self.invoice_id, :tax => newTax)

      newTotal = self.amount + newTax

      Invoice.update(self.invoice_id, :total => newTotal)
    end
  end

  def auto_create_invoice
    if self.invoice_id.nil?
      self.invoice = Invoice.create(customer_id: self.vehicle.customer_id)
    end
  end

  def list_open_jobs
    select([:job_id, :job_comments]).where(complete: false)


  end



end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :job
  belongs_to :service
  belongs_to :employee

  after_save :update_job_amount
  after_save :update_job_status
  after_update :update_job_amount_subtract





  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Complete"
    else
      "In Progress"
    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount

    if self.complete?

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount + x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)


    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount_subtract

    if self.complete == false

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount - x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)

    end
  end



  def update_job_status
    x = true
    j = Job.find(self.job_id)

    j.line_items.each do |line|
      if line.complete?
      else
        x = false
      end

      j.complete = x
      j.save
    end
  end



  def self.compare_hours

    hours = 0
    LineItem.all.each do |line|
      line.complete?
      hours += line.labor_hrs - Service.find(line.service_id).flag_hrs
    end

    return hours
  end



end

app/models/make.rb
class Make < ActiveRecord::Base

  has_many :vehicles
end

app/models/model.rb
class Model < ActiveRecord::Base

  has_many :vehicles
end

app/models/report.rb
class Report < ActiveRecord::Base

  def invoice_totals
    self.invoice.select("sum(total).group(self.invoice_id)")
  end

  def show_veh_info
    "#{self.customer.show_full_name}  - #{self.year.mod_year} #{self.make.name} #{self.model.name} #{self.color.name}"
  end

end

app/models/service.rb
class Service < ActiveRecord::Base

  has_many :line_items

end

app/models/transmission.rb
class Transmission < ActiveRecord::Base
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer
  belongs_to :make
  belongs_to :model
  belongs_to :year
  belongs_to :color
  belongs_to :engine
  belongs_to :transmission
  belongs_to :chassis


  def show_veh_info
    "#{self.customer.show_full_name}  - #{self.year.mod_year} #{self.make.name} #{self.model.name} #{self.color.name}"
  end

end

app/models/year.rb
class Year < ActiveRecord::Base

  has_many :vehicles
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:fname, :lname, :phone, :email, :street, :city, :state, :zip, :start_date, :status, :pay_rate)
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname, "First Name"  %><br>
    <%= f.text_field :fname, :placeholder => "John" %>
  </div>
  <div class="field">
    <%= f.label :lname, "Last Name" %><br>
    <%= f.text_field :lname, :placeholder => "Smith" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, :placeholder => "XXXXXXXXXX" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :placeholder => "xxx@xxx.com" %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street, :placeholder => "xxx street name" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, :placeholder => "Houston" %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip, :placeholder => "77XXX" %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :status,"Active"%><br>
    <%= f.check_box :show_active %>
  </div>
  <div class="field">
    <%= f.label :pay_rate %><br>
    <%= f.text_field :pay_rate, :placeholder => "0.XX%" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<div>
  <%= button_to "Show Employee", @employee, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Employess", employees_path, :class => "button", :method => :get  %>
</div>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table class="table table-striped table-hover DataTables">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Start Date</th>
      <th>Active</th>
      <th>Pay Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.fname %></td>
        <td><%= employee.lname %></td>
        <td><%= number_to_phone(employee.phone, area_code: true) %></td>
        <td><%= employee.email %></td>
        <td><%= employee.street %></td>
        <td><%= employee.city %></td>
        <td><%= employee.state %></td>
        <td><%= employee.zip %></td>
        <td><%= employee.start_date %></td>
        <td><%= employee.show_active %></td>
        <td><%= employee.pay_rate %></td>
        <td class="btn btn-success"><%= link_to 'Show', employee %></td>
        <td class="btn btn-warning"><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td class="btn btn-danger"><%= link_to 'Terminate', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= button_to "Create New Enployee", new_employee_path, :class => "button", :method => :get  %>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<div>
  <%= button_to "Back to Employees", employees_path, :class => "button", :method => :get  %>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @employee.fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @employee.lname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= number_to_phone(@employee.phone, area_code: true) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Street:</strong>
  <%= @employee.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @employee.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @employee.zip %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @employee.start_date %>
</p>

<p>
  <strong>Active:</strong>
  <%= @employee.show_active %>
</p>

<p>
  <strong>Pay Rate:</strong>
  <%= @employee.pay_rate %>
</p>



<div>
  <%= button_to "Edit Employee", edit_employee_path(@employee), :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Employees", employees_path, :class => "button", :method => :get  %>
</div>