config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :transmissions

  resources :colors

  resources :chasses

  resources :engines

  resources :years

  resources :models

  resources :makes

  resources :emp_jobs

  resources :line_items

  resources :vehicles

  resources :jobs

  resources :appointments

  resources :invoices

  resources :services

  resources :employees

  resources :customers

  resources :surplus_products

  get "/update_price" => "services#update_price"

  root 'customers#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :job


  validates_uniqueness_of :date, scope: [], :message=>"This time is already taken. Please select another time."

end

app/models/chassis.rb
class Chassis < ActiveRecord::Base

  has_many :vehicles
end

app/models/color.rb
class Color < ActiveRecord::Base

  has_many :vehicles
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :invoices
  has_many :vehicles


  def show_full_name
    "#{fname} #{lname}"
  end

end

app/models/emp_job.rb
class EmpJob < ActiveRecord::Base

  # belongs_to :employee
  # belongs_to :job
end

app/models/employee.rb
class Employee < ActiveRecord::Base

  # has_many :emp_jobs
  # has_many :jobs, through: :emp_jobs

  has_many :jobs
  has_many :line_items


  def show_full_name
    "#{fname} #{lname}"
  end


  def show_active
    if status?
      "Active"
    else
      "Inactive"
    end
  end
end

app/models/engine.rb
class Engine < ActiveRecord::Base

  has_many :vehicles
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer


  def show_paid
    if paid?
      "Paid"
    else
      "Due"
    end
  end

end

app/models/job.rb
class Job < ActiveRecord::Base

  has_many :appointments
  has_many :line_items, dependent: :destroy
  has_many :surplus_products
  # has_many :emp_jobs
  # has_many :employees, through: :emp_jobs

  belongs_to :employee
  belongs_to :vehicle
  belongs_to :invoice, dependent: :destroy


  before_create :auto_create_invoice
  after_update :update_invoice_subtotal


  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Finished"
    else
      "In Progress"
    end
  end

  #when a job is marked complete, update invoice subtotal
  def update_invoice_subtotal
    if self.complete?
      Invoice.update(self.invoice_id, :subtotal => self.amount)

      newTax = self.amount * 0.0625

      Invoice.update(self.invoice_id, :tax => newTax)

      newTotal = self.amount + newTax

      Invoice.update(self.invoice_id, :total => newTotal)
    end
  end

  def auto_create_invoice
    if self.invoice_id.nil?
      self.invoice = Invoice.create(customer_id: self.vehicle.customer_id)
    end
  end

  def list_open_jobs
    select([:job_id, :job_comments]).where(complete: false)


  end



end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :job
  belongs_to :service
  belongs_to :employee

  after_save :update_job_amount
  after_save :update_job_status
  after_update :update_job_amount_subtract





  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Complete"
    else
      "In Progress"
    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount

    if self.complete?

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount + x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)


    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount_subtract

    if self.complete == false

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount - x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)

    end
  end



  def update_job_status
    x = true
    j = Job.find(self.job_id)

    j.line_items.each do |line|
      if line.complete?
      else
        x = false
      end

      j.complete = x
      j.save
    end
  end



  def self.compare_hours

    hours = 0
    LineItem.all.each do |line|
      line.complete?
      hours += line.labor_hrs - Service.find(line.service_id).flag_hrs
    end

    return hours
  end



end

app/models/make.rb
class Make < ActiveRecord::Base

  has_many :vehicles
end

app/models/model.rb
class Model < ActiveRecord::Base

  has_many :vehicles
end

app/models/report.rb
class Report < ActiveRecord::Base

  def invoice_totals
    self.invoice.select("sum(total).group(self.invoice_id)")
  end

  def show_veh_info
    "#{self.customer.show_full_name}  - #{self.year.mod_year} #{self.make.name} #{self.model.name} #{self.color.name}"
  end

end

app/models/service.rb
class Service < ActiveRecord::Base

  has_many :line_items

end

app/models/transmission.rb
class Transmission < ActiveRecord::Base
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer
  belongs_to :make
  belongs_to :model
  belongs_to :year
  belongs_to :color
  belongs_to :engine
  belongs_to :transmission
  belongs_to :chassis


  def show_veh_info
    "#{self.customer.show_full_name}  - #{self.year.mod_year} #{self.make.name} #{self.model.name} #{self.color.name}"
  end

end

app/models/year.rb
class Year < ActiveRecord::Base

  has_many :vehicles
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colors_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:name)
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/models_helper.rb
module ModelsHelper




end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/colors/_form.html.erb
<%= form_for(@color) do |f| %>
  <% if @color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% @color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing Color</h1>

<%= render 'form' %>

<%= link_to 'Show', @color %> |
<%= link_to 'Back', colors_path %>

<div>
  <%= button_to "Show Exterior Color", @color, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Exterior Color", colors_path, :class => "button", :method => :get  %>
</div>

app/views/colors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exterior Colors</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colors.each do |color| %>
      <tr>
        <td><%= color.name %></td>
        <td class="btn btn-success"><%= link_to 'Show', color %></td>
        <td class="btn btn-warning"><%= link_to 'Edit', edit_color_path(color) %></td>
        <td class="btn btn-danger"><%= link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= button_to "Create New Exterior Color", new_color_path, :class => "button", :method => :get  %>
</div>

app/views/colors/new.html.erb
<h1>New Color</h1>

<%= render 'form' %>

<br>
<div>
  <%= button_to "Back to Exterior Color", colors_path, :class => "button", :method => :get  %>
</div>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @color.name %>
</p>


<div>
  <%= button_to "Edit Exterior Color", edit_color_path, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Exterior Color", colors_path, :class => "button", :method => :get  %>
</div>